name: Waka Readme Stats

on:
  schedule:
    - cron: '30 18 * * *' 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_LOC_CHART: false
          SHOW_LANGUAGE: true
          SHOW_TIMEZONE: false
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: false
          SHOW_UPDATED_DATE: true
          SHOW_SHORT_INFO: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
